# frozen_string_literal: true

# Base class for the customer assistant's in-process LLM tools.
#
# Context (account + organization) is injected at construction and NEVER read from tool arguments,
# because arguments are generated by the model and must be treated as untrusted user input. All
# reads go through `scoped`, which combines the Pundit policy scope with an explicit organization
# filter — a foreign id can only ever behave as "not found".
module Assistant
  class BaseTool < RubyLLM::Tool
    # WHY these are not in config/locales: they are model-facing, not user-facing. The assistant
    # answers in the user's language and relays these conversationally, so one English string
    # serves all locales (same reasoning as AssistantPrompt).
    UNAVAILABLE_MESSAGE = 'This tool is temporarily unavailable. Please try again in a few minutes.'
    FAILED_MESSAGE = 'This tool failed unexpectedly. Try again or rephrase the request.'

    # WHY StatementInvalid counts as infrastructure: tools never interpolate raw SQL from arguments
    # (enums are allow-listed, ILIKE terms sanitized), so a StatementInvalid at runtime means the
    # database itself failed mid-query, not that the model sent a bad value.
    INFRASTRUCTURE_ERRORS = [
      ActiveRecord::ConnectionNotEstablished,
      ActiveRecord::ConnectionTimeoutError,
      ActiveRecord::StatementInvalid,
      PG::Error
    ].freeze

    def initialize(account:, organization:)
      @account = account
      @organization = organization
    end

    # WHY: ruby_llm derives the tool name from the full class name, which would include the module
    # ("assistant--conversation_list"). Demodulized names are what the system prompt references.
    def name
      self.class.name.demodulize.underscore.delete_suffix('_tool')
    end

    # WHY the rescues live in `call` (the gem's entry point) and not in each `execute`: ruby_llm
    # 1.11 has no rescue around tool execution, so an exception here would abort the whole streamed
    # turn. Catching everything and returning an { error: } payload lets the model explain the
    # failure to the user and keep the conversation going.
    #
    # WHY JSON strings: ruby_llm 1.11 stores hash results via `to_s` (Ruby inspect format); JSON is
    # a cleaner, deterministic payload for the model.
    def call(args)
      result = super
      result.is_a?(String) ? result : JSON.generate(result)
    rescue Pundit::NotAuthorizedError
      Rails.logger.warn("[AssistantTool] #{name} denied for account ##{@account.id}")
      error_payload('You are not allowed to do that.')
    rescue ArgumentError => e
      # e.message here is Ruby's own keyword-argument error ("unknown keyword: :foo"), safe to
      # relay so the model can correct its call.
      error_payload("Invalid arguments: #{e.message}")
    rescue *INFRASTRUCTURE_ERRORS => e
      Rails.logger.error("[AssistantTool] #{name} infrastructure failure: #{e.class}: #{e.message}")
      error_payload(UNAVAILABLE_MESSAGE)
    rescue StandardError => e
      Rails.logger.error("[AssistantTool] #{name} failed: #{e.class}: #{e.message}")
      error_payload(FAILED_MESSAGE)
    end

    private

    attr_reader :account, :organization

    def error_payload(message)
      JSON.generate({ error: message })
    end

    def scoped(klass)
      Pundit.policy_scope!(account, klass).where(organization_id: organization.id)
    end

    def authorize!(record, query)
      Pundit.authorize(account, record, query)
    end
  end
end
